"""SQLAlchemy models for the origofs metadata store.

These declarative models mirror, table-for-table, the metadata schema the Rust
engine builds in ``crates/origofs-core/src/migrations.rs`` — the *names and
versions* half of the design's metadata/content split (``docs/DESIGN.md`` §3,
§4b, §5). They describe **only** the metadata database; content (chunks and the
immutable blob/tree/commit objects) lives in the content store, referenced here
by hash only — never as bytes in a column.

Why they exist: so a Python application can manage this schema with Alembic
(``origofs.db.migrations``) and query it with SQLAlchemy, instead of relying
solely on the engine's built-in migrator. The schema this metadata declares is
kept byte-for-byte compatible with what the engine produces so the two can open
the same database — see ``origofs.db.migrations`` for how the two migration
ledgers (Alembic's ``alembic_version`` and the engine's ``schema_meta``)
coexist.

Dual dialect, one definition
----------------------------
The core schema uses ``INTEGER`` on SQLite and ``BIGINT`` on Postgres for the
same logical column (SQLite has one integer class; an autoincrement primary key
must be ``INTEGER`` there to alias ``rowid``). :data:`BigInt` reproduces that
split from a single column definition, so these models emit the matching type on
either backend. Identity primary keys render ``GENERATED BY DEFAULT AS IDENTITY``
on Postgres and ``INTEGER PRIMARY KEY AUTOINCREMENT`` on SQLite, exactly as the
engine's migrations do.

The physical column *order* is not load-bearing: the engine never issues
``SELECT *`` or a positional ``INSERT`` — every statement names its columns — so
a table these models create is interchangeable with one the engine created.
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import (
    BigInteger,
    Identity,
    Index,
    Integer,
    PrimaryKeyConstraint,
    Text,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# BIGINT on Postgres, INTEGER on SQLite — the same dual-dialect split the core
# migrations author by hand. Reused across every integer column so a single
# model definition emits the right type on either backend.
BigInt = BigInteger().with_variant(Integer(), "sqlite")


class Base(DeclarativeBase):
    """Declarative base; ``Base.metadata`` is the Alembic autogenerate target."""


#: The schema version these models describe — the highest migration in
#: ``crates/origofs-core/src/migrations.rs`` (``latest_schema_version()``). The
#: initial Alembic revision seeds ``schema_meta`` up to this value so the engine
#: recognises an Alembic-created database as fully migrated.
SCHEMA_VERSION = 13


# --- migration bookkeeping ---------------------------------------------------


class SchemaMeta(Base):
    """The engine's own migration ledger (one row per applied core migration).

    Created by the engine outside the numbered migration list; modelled here so
    Alembic can create and seed it, keeping an Alembic-provisioned database
    readable by the engine without it re-running (and, for V11/V13, rebuilding)
    migrations it thinks are pending. Distinct from Alembic's own
    ``alembic_version`` table.
    """

    __tablename__ = "schema_meta"

    version: Mapped[int] = mapped_column(BigInt, primary_key=True, autoincrement=False)
    applied_at: Mapped[int] = mapped_column(BigInt, nullable=False)


# --- V11: multi-workspace registry -------------------------------------------


class Workspace(Base):
    """One row per workspace sharing the store; each owns a root inode."""

    __tablename__ = "workspace"
    __table_args__ = {"sqlite_autoincrement": True}

    id: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    root_ino: Mapped[int] = mapped_column(BigInt, nullable=False)
    created_at: Mapped[int] = mapped_column(BigInt, nullable=False)


# --- V1: working tree (mutable overlay over a base commit) -------------------


class Inode(Base):
    """A filesystem object. ``content_hash`` references the content store."""

    __tablename__ = "inode"
    __table_args__ = (
        Index("idx_inode_workspace", "workspace_id"),
        {"sqlite_autoincrement": True},
    )

    ino: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    mode: Mapped[int] = mapped_column(BigInt, nullable=False)
    nlink: Mapped[int] = mapped_column(BigInt, nullable=False, server_default=text("1"))
    size: Mapped[int] = mapped_column(BigInt, nullable=False, server_default=text("0"))
    content_hash: Mapped[Optional[str]] = mapped_column(Text)
    mtime: Mapped[int] = mapped_column(BigInt, nullable=False)
    ctime: Mapped[int] = mapped_column(BigInt, nullable=False)
    # Added in V11 so a per-workspace checkout clears only its own tree.
    workspace_id: Mapped[int] = mapped_column(
        BigInt, nullable=False, server_default=text("1")
    )


class Dentry(Base):
    """Directory entry: a ``name`` under ``parent_ino`` pointing at ``ino``."""

    __tablename__ = "dentry"
    __table_args__ = (
        PrimaryKeyConstraint("parent_ino", "name"),
        Index("idx_dentry_ino", "ino"),
    )

    parent_ino: Mapped[int] = mapped_column(BigInt, autoincrement=False)
    name: Mapped[str] = mapped_column(Text)
    ino: Mapped[int] = mapped_column(BigInt, nullable=False)


class Symlink(Base):
    """The target path of a symlink inode."""

    __tablename__ = "symlink"

    ino: Mapped[int] = mapped_column(BigInt, primary_key=True, autoincrement=False)
    target: Mapped[str] = mapped_column(Text, nullable=False)


# --- V2: versioning refs + workspace config ----------------------------------


class Ref(Base):
    """A ref (branch/tag/HEAD) → value, per workspace."""

    __tablename__ = "ref"
    __table_args__ = (PrimaryKeyConstraint("workspace_id", "name"),)

    # workspace_id folded into the PK in V11 (every workspace has its own HEAD).
    workspace_id: Mapped[int] = mapped_column(
        BigInt, autoincrement=False, server_default=text("1")
    )
    name: Mapped[str] = mapped_column(Text)
    value: Mapped[str] = mapped_column(Text, nullable=False)


class Config(Base):
    """Per-workspace key/value config (e.g. versioning mode)."""

    __tablename__ = "config"
    __table_args__ = (PrimaryKeyConstraint("workspace_id", "key"),)

    workspace_id: Mapped[int] = mapped_column(
        BigInt, autoincrement=False, server_default=text("1")
    )
    key: Mapped[str] = mapped_column(Text)
    value: Mapped[str] = mapped_column(Text, nullable=False)


# --- V3: merge conflicts + LFS-style file locks ------------------------------


class Conflict(Base):
    """A recorded merge conflict at ``path``."""

    __tablename__ = "conflict"
    __table_args__ = (PrimaryKeyConstraint("workspace_id", "path"),)

    workspace_id: Mapped[int] = mapped_column(
        BigInt, autoincrement=False, server_default=text("1")
    )
    path: Mapped[str] = mapped_column(Text)
    kind: Mapped[str] = mapped_column(Text, nullable=False)


class FileLock(Base):
    """An exclusive (git-LFS-style) lock on a binary path."""

    __tablename__ = "file_lock"
    __table_args__ = (PrimaryKeyConstraint("workspace_id", "path"),)

    workspace_id: Mapped[int] = mapped_column(
        BigInt, autoincrement=False, server_default=text("1")
    )
    path: Mapped[str] = mapped_column(Text)
    owner: Mapped[str] = mapped_column(Text, nullable=False)
    acquired_at: Mapped[int] = mapped_column(BigInt, nullable=False)


# --- V4/V9/V10: attribution — actors, sessions, audit, op-log, blame ---------


class Actor(Base):
    """A human or agent identity; every attributed write names one."""

    __tablename__ = "actor"
    __table_args__ = (
        # V9: at most one actor per external identity (partial: NULLs are free).
        Index(
            "idx_actor_auth_subject",
            "auth_subject",
            unique=True,
            sqlite_where=text("auth_subject IS NOT NULL"),
            postgresql_where=text("auth_subject IS NOT NULL"),
        ),
        {"sqlite_autoincrement": True},
    )

    id: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    auth_subject: Mapped[Optional[str]] = mapped_column(Text)
    agent_model: Mapped[Optional[str]] = mapped_column(Text)
    agent_vendor: Mapped[Optional[str]] = mapped_column(Text)
    controller_actor_id: Mapped[Optional[int]] = mapped_column(BigInt)
    created_at: Mapped[int] = mapped_column(BigInt, nullable=False)
    # V10: 0 = direct (may write to the tree), 1 = propose (must go via review).
    write_policy: Mapped[int] = mapped_column(
        BigInt, nullable=False, server_default=text("0")
    )


class Session(Base):
    """A run of work by one actor; groups edits for ``revert_session``."""

    __tablename__ = "session"
    __table_args__ = {"sqlite_autoincrement": True}

    id: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    actor_id: Mapped[int] = mapped_column(BigInt, nullable=False)
    client: Mapped[Optional[str]] = mapped_column(Text)
    started_at: Mapped[int] = mapped_column(BigInt, nullable=False)
    ended_at: Mapped[Optional[int]] = mapped_column(BigInt)


class ToolCall(Base):
    """The agent tool-call audit log (retained from agentfs)."""

    __tablename__ = "tool_calls"
    __table_args__ = {"sqlite_autoincrement": True}

    id: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    session_id: Mapped[Optional[int]] = mapped_column(BigInt)
    actor_id: Mapped[Optional[int]] = mapped_column(BigInt)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    parameters: Mapped[Optional[str]] = mapped_column(Text)
    result: Mapped[Optional[str]] = mapped_column(Text)
    error: Mapped[Optional[str]] = mapped_column(Text)
    started_at: Mapped[int] = mapped_column(BigInt, nullable=False)
    completed_at: Mapped[int] = mapped_column(BigInt, nullable=False)
    duration_ms: Mapped[int] = mapped_column(BigInt, nullable=False)


class EditOp(Base):
    """The append-only, ground-truth op-log: one row per attributed write."""

    __tablename__ = "edit_op"
    __table_args__ = (
        Index("idx_edit_op_actor", "actor_id"),
        Index("idx_edit_op_session", "session_id"),
        Index("idx_edit_op_workspace", "workspace_id"),  # V12
        {"sqlite_autoincrement": True},
    )

    id: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    session_id: Mapped[Optional[int]] = mapped_column(BigInt)
    actor_id: Mapped[int] = mapped_column(BigInt, nullable=False)
    tool_call_id: Mapped[Optional[int]] = mapped_column(BigInt)
    ino: Mapped[int] = mapped_column(BigInt, nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    op: Mapped[str] = mapped_column(Text, nullable=False)
    byte_start: Mapped[int] = mapped_column(BigInt, nullable=False)
    byte_len: Mapped[int] = mapped_column(BigInt, nullable=False)
    pre_hash: Mapped[Optional[str]] = mapped_column(Text)
    post_hash: Mapped[Optional[str]] = mapped_column(Text)
    ts: Mapped[int] = mapped_column(BigInt, nullable=False)
    # V12: workspace-scope the op-log so it isolates like the working tree.
    workspace_id: Mapped[int] = mapped_column(
        BigInt, nullable=False, server_default=text("1")
    )


class LineBlame(Base):
    """Per-inode line authorship runs (V4). Superseded for durability by
    :class:`BlobBlame` (V8/V13) but retained by the engine."""

    __tablename__ = "line_blame"

    ino: Mapped[int] = mapped_column(BigInt, primary_key=True, autoincrement=False)
    runs: Mapped[str] = mapped_column(Text, nullable=False)


# --- V5/V6/V12: live collaboration — change feed + presence ------------------


class FsEvent(Base):
    """The append-only change feed (one row per filesystem event)."""

    __tablename__ = "fs_event"
    __table_args__ = (
        Index("idx_fs_event_seq", "seq"),
        Index("idx_fs_event_workspace", "workspace_id"),  # V12
        {"sqlite_autoincrement": True},
    )

    seq: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    actor_id: Mapped[Optional[int]] = mapped_column(BigInt)
    session_id: Mapped[Optional[int]] = mapped_column(BigInt)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    detail: Mapped[Optional[str]] = mapped_column(Text)
    ts: Mapped[int] = mapped_column(BigInt, nullable=False)
    branch: Mapped[Optional[str]] = mapped_column(Text)  # V6
    workspace_id: Mapped[int] = mapped_column(
        BigInt, nullable=False, server_default=text("1")
    )


class Presence(Base):
    """Per-session presence: where each live session last was."""

    __tablename__ = "presence"
    __table_args__ = (
        Index("idx_presence_last_seen", "last_seen"),
        Index("idx_presence_workspace", "workspace_id"),  # V12
    )

    session_id: Mapped[int] = mapped_column(
        BigInt, primary_key=True, autoincrement=False
    )
    actor_id: Mapped[int] = mapped_column(BigInt, nullable=False)
    path: Mapped[Optional[str]] = mapped_column(Text)
    last_seen: Mapped[int] = mapped_column(BigInt, nullable=False)
    workspace_id: Mapped[int] = mapped_column(
        BigInt, nullable=False, server_default=text("1")
    )


# --- V7/V12: agent-suggestion review queue -----------------------------------


class Suggestion(Base):
    """A proposed edit held for human review. ``base_hash``/``proposed_hash``
    reference content in the CAS; this row is just the review record."""

    __tablename__ = "suggestion"
    __table_args__ = (
        Index("idx_suggestion_status", "status"),
        Index("idx_suggestion_path", "path"),
        Index("idx_suggestion_workspace", "workspace_id"),  # V12
        {"sqlite_autoincrement": True},
    )

    id: Mapped[int] = mapped_column(BigInt, Identity(), primary_key=True)
    actor_id: Mapped[int] = mapped_column(BigInt, nullable=False)
    session_id: Mapped[Optional[int]] = mapped_column(BigInt)
    branch: Mapped[Optional[str]] = mapped_column(Text)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    base_hash: Mapped[Optional[str]] = mapped_column(Text)
    proposed_hash: Mapped[Optional[str]] = mapped_column(Text)
    summary: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    created_ts: Mapped[int] = mapped_column(BigInt, nullable=False)
    resolved_ts: Mapped[Optional[int]] = mapped_column(BigInt)
    resolved_by: Mapped[Optional[int]] = mapped_column(BigInt)
    workspace_id: Mapped[int] = mapped_column(
        BigInt, nullable=False, server_default=text("1")
    )


# --- V8/V13: blame keyed by content hash (survives checkout/merge) -----------


class BlobBlame(Base):
    """Per-line authorship keyed by ``(workspace_id, content_hash)`` so blame
    follows the content across checkout and merge (V8; workspace-scoped in V13)."""

    __tablename__ = "blob_blame"
    __table_args__ = (PrimaryKeyConstraint("workspace_id", "content_hash"),)

    workspace_id: Mapped[int] = mapped_column(
        BigInt, autoincrement=False, server_default=text("1")
    )
    content_hash: Mapped[str] = mapped_column(Text)
    runs: Mapped[str] = mapped_column(Text, nullable=False)


__all__ = [
    "Base",
    "BigInt",
    "SCHEMA_VERSION",
    "SchemaMeta",
    "Workspace",
    "Inode",
    "Dentry",
    "Symlink",
    "Ref",
    "Config",
    "Conflict",
    "FileLock",
    "Actor",
    "Session",
    "ToolCall",
    "EditOp",
    "LineBlame",
    "FsEvent",
    "Presence",
    "Suggestion",
    "BlobBlame",
]
