"""initial schema

Mirrors ``crates/origofs-core/src/migrations.rs`` V1 through V13 in full:
every table the Rust engine's own migrator builds, created here from
``origofs.db.models.Base.metadata`` (the single source of truth for the
schema shared with the engine) so this revision can never drift from it.

After creating the tables, seeds the same bootstrap rows the engine's
``MetadataStore::init`` writes into a brand-new store — the ``default``
workspace, its root directory inode, and ``schema_meta`` stamped through
the latest version these models describe — so a database Alembic creates is
immediately recognized by the engine as fully migrated. Without this seed,
opening an Alembic-provisioned store with the engine would treat migrations
1-13 as still pending and re-apply them, which for V11/V13 means rebuilding
tables that already hold Alembic-created rows.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-29

"""
import time
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from origofs.db.models import SCHEMA_VERSION, Base

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The engine's own bootstrap inserts the root directory with this exact mode
# (crates/origofs-core/src/{sqlite,postgres}.rs DIR_MODE); ino=1/workspace_id=1
# are INO_ROOT and the `default` workspace (types.rs, sqlite.rs/postgres.rs
# DEFAULT_WORKSPACE).
_DIR_MODE = 0o040755
_DEFAULT_WORKSPACE = 1
_ROOT_INO = 1


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind, checkfirst=True)
    _seed_bootstrap_rows(bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind)


def _seed_bootstrap_rows(bind) -> None:
    now = int(time.time())
    dialect = bind.dialect.name

    if dialect == "sqlite":
        bind.execute(
            sa.text(
                "INSERT OR IGNORE INTO workspace(id, name, root_ino, created_at) "
                "VALUES (:id, 'default', :root_ino, :now)"
            ),
            {"id": _DEFAULT_WORKSPACE, "root_ino": _ROOT_INO, "now": now},
        )
        bind.execute(
            sa.text(
                "INSERT OR IGNORE INTO inode"
                "(ino, workspace_id, kind, mode, nlink, size, content_hash, mtime, ctime) "
                "VALUES (:ino, :ws, 'dir', :mode, 1, 0, NULL, :now, :now)"
            ),
            {"ino": _ROOT_INO, "ws": _DEFAULT_WORKSPACE, "mode": _DIR_MODE, "now": now},
        )
    else:
        # Postgres: match crates/origofs-core/src/postgres.rs `init` exactly,
        # including advancing the identity sequence past the explicitly-seeded id
        # (an inserted value never bumps a GENERATED BY DEFAULT AS IDENTITY
        # sequence on its own).
        bind.execute(
            sa.text(
                "INSERT INTO workspace(id, name, root_ino, created_at) "
                "VALUES (:id, 'default', :root_ino, :now) ON CONFLICT DO NOTHING"
            ),
            {"id": _DEFAULT_WORKSPACE, "root_ino": _ROOT_INO, "now": now},
        )
        bind.execute(
            sa.text(
                "SELECT setval(pg_get_serial_sequence('workspace', 'id'), "
                "GREATEST((SELECT MAX(id) FROM workspace), 1))"
            )
        )
        bind.execute(
            sa.text(
                "INSERT INTO inode"
                "(ino, workspace_id, kind, mode, nlink, size, content_hash, mtime, ctime) "
                "VALUES (:ino, :ws, 'dir', :mode, 1, 0, NULL, :now, :now) "
                "ON CONFLICT (ino) DO NOTHING"
            ),
            {"ino": _ROOT_INO, "ws": _DEFAULT_WORKSPACE, "mode": _DIR_MODE, "now": now},
        )
        bind.execute(
            sa.text(
                "SELECT setval(pg_get_serial_sequence('inode', 'ino'), "
                "(SELECT MAX(ino) FROM inode))"
            )
        )

    # Stamp schema_meta through SCHEMA_VERSION, so the engine's own migrator
    # (crates/origofs-core/src/migrations.rs) sees a fully-migrated store on
    # first open and never re-applies (or, for V11/V13, rebuilds) a migration
    # whose tables Alembic already created.
    ignore = "OR IGNORE " if dialect == "sqlite" else ""
    conflict_clause = "" if dialect == "sqlite" else " ON CONFLICT (version) DO NOTHING"
    stmt = sa.text(
        f"INSERT {ignore}INTO schema_meta(version, applied_at) "
        f"VALUES (:v, :now){conflict_clause}"
    )
    for version in range(1, SCHEMA_VERSION + 1):
        bind.execute(stmt, {"v": version, "now": now})
