"""Type stubs for the origofs package (re-exported from the ``origofs._origofs`` extension).

Every I/O method is async (returns an awaitable) so it composes with FastAPI's
`async def` handlers. Structured results are plain ``dict``/``list`` objects,
directly JSON-serializable.
"""
from __future__ import annotations
from typing import Any, Optional

class OrigoFSError(Exception):
    """Base origofs error (raised for errors without a more specific mapping)."""

class ConflictError(OrigoFSError):
    """A suggestion's base changed since it was proposed (stale base)."""

class WriteCtx:
    """The actor context to attribute a write to."""
    @staticmethod
    def actor(actor: int) -> "WriteCtx": ...
    @staticmethod
    def session(actor: int, session: int) -> "WriteCtx": ...
    @property
    def actor_id(self) -> int: ...
    @property
    def session_id(self) -> Optional[int]: ...

class S3Config:
    """Connection settings for an S3-compatible object store (S3/R2/MinIO, or GCS
    via its S3-interop XML API). For GCS, set ``endpoint`` to
    ``https://storage.googleapis.com`` and pass GCS HMAC interop keys; for native
    GCS auth use :class:`GcsConfig` instead."""
    def __init__(
        self,
        bucket: str,
        region: str,
        endpoint: Optional[str] = None,
        allow_http: bool = False,
        access_key_id: Optional[str] = None,
        secret_access_key: Optional[str] = None,
        prefix: Optional[str] = None,
    ) -> None: ...

class GcsConfig:
    """Connection settings for a native Google Cloud Storage object store (GCS JSON
    API + OAuth2). Credentials resolve as: explicit ``service_account_key`` (inline
    JSON) or ``service_account_path`` (file); then Application Default Credentials
    (``application_credentials``, else ``GOOGLE_APPLICATION_CREDENTIALS`` /
    ``gcloud``); then the GCE/GKE metadata server (workload identity)."""
    def __init__(
        self,
        bucket: str,
        service_account_path: Optional[str] = None,
        service_account_key: Optional[str] = None,
        application_credentials: Optional[str] = None,
        prefix: Optional[str] = None,
    ) -> None: ...

class Mount:
    """A live FUSE mount; unmounts on ``unmount()``, ``with``-exit, or drop."""
    def unmount(self) -> None: ...
    def __enter__(self) -> "Mount": ...
    def __exit__(self, *args: Any) -> None: ...

class Subscription:
    """A push subscription to the change feed (Postgres LISTEN/NOTIFY)."""
    async def recv(self) -> list[dict[str, Any]]: ...

class CoeditSyncReply:
    """The routing for one processed y-sync payload (see ``CoeditDoc.handle_sync``)."""
    @property
    def reply(self) -> bytes:
        """Frames to send back to the originating connection (``b""`` if none)."""
        ...
    @property
    def broadcast(self) -> bytes:
        """Frames to fan out to the room's other connections (``b""`` if none)."""
        ...

class CoeditDoc:
    """A live co-edited document (roadmap M8): a Yjs-compatible CRDT whose inserts
    are attributed per byte range. Obtain a server-side room doc from
    ``Workspace.open_coedit`` and drive it with the Yjs y-sync wire protocol via
    ``handle_sync`` so an unmodified editor (PlateJS, ``y-websocket``) collaborates
    directly; land it with ``Workspace.checkpoint_coedit``. Safe to share one
    instance across many concurrent WebSocket handlers."""
    def __init__(self) -> None:
        """A fresh, empty document (for a Python-side agent or a test client)."""
        ...
    async def insert(self, ctx: WriteCtx, index: int, chunk: str) -> None:
        """Insert ``chunk`` at character ``index`` (UTF-16 offset), attributed to ``ctx``."""
        ...
    async def remove(self, index: int, length: int) -> None:
        """Remove ``length`` characters starting at ``index`` (UTF-16 offsets)."""
        ...
    async def sync_start(self) -> bytes:
        """The y-sync ``SyncStep1`` frame to greet a new client with."""
        ...
    async def handle_sync(self, ctx: WriteCtx, data: bytes) -> CoeditSyncReply:
        """Handle one inbound y-sync payload from a connection authenticated as
        ``ctx``; its content is attributed to ``ctx`` server-side."""
        ...
    async def apply_relayed(self, frame: bytes) -> None:
        """Merge a y-sync frame relayed from another worker (already attributed by
        its origin) without re-attribution — the cross-worker relay's apply path.
        Idempotent."""
        ...
    async def text(self) -> str:
        """The full current text."""
        ...

class CoeditRelayNote:
    """One relayed co-editing update from another worker (see
    ``Workspace.coedit_subscribe`` / ``coedit_replay``)."""
    @property
    def seq(self) -> int: ...
    @property
    def origin(self) -> str:
        """The publishing worker's id (skip your own)."""
        ...
    @property
    def path(self) -> str: ...
    @property
    def delta(self) -> bytes:
        """The update payload (a y-sync frame) to feed ``CoeditDoc.apply_relayed``."""
        ...

class CoeditRelaySub:
    """A live subscription to the cross-worker co-editing relay (Postgres
    LISTEN/NOTIFY). Returned by ``Workspace.coedit_subscribe``."""
    async def recv(self) -> list[CoeditRelayNote]:
        """Block until peers publish, then return their updates in ``seq`` order
        (``[]`` once the connection closes)."""
        ...

class Workspace:
    # --- constructors (async) ---
    @staticmethod
    async def open_local(db_path: str, cas_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_local_packed(db_path: str, data_dir: str, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg(dsn: str, cas_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_s3(db_path: str, cfg: S3Config) -> "Workspace": ...
    @staticmethod
    async def open_s3_packed(db_path: str, cfg: S3Config, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg_s3(dsn: str, cfg: S3Config) -> "Workspace": ...
    @staticmethod
    async def open_pg_s3_packed(dsn: str, cfg: S3Config, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_gcs(db_path: str, cfg: GcsConfig) -> "Workspace": ...
    @staticmethod
    async def open_gcs_packed(db_path: str, cfg: GcsConfig, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg_gcs(dsn: str, cfg: GcsConfig) -> "Workspace": ...
    @staticmethod
    async def open_pg_gcs_packed(dsn: str, cfg: GcsConfig, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_object_memory(db_path: str) -> "Workspace": ...

    # --- files ---
    async def read(self, path: str) -> bytes: ...
    async def write(self, path: str, data: bytes) -> None: ...
    async def write_as(self, ctx: WriteCtx, path: str, data: bytes) -> None: ...
    async def mkdir_p(self, path: str) -> None: ...
    async def ls(self, path: str) -> list[dict[str, Any]]: ...
    async def stat(self, path: str) -> dict[str, Any]: ...
    async def remove(self, path: str) -> None: ...
    async def rename(self, from_: str, to: str) -> None: ...

    # --- versioning ---
    async def commit(self, author: str, message: str) -> str: ...
    async def log(self) -> list[dict[str, Any]]: ...
    async def status(self) -> list[dict[str, Any]]: ...
    async def diff(self, from_: str, to: str) -> list[dict[str, Any]]: ...
    async def diff_file(self, from_: str, to: str, path: str) -> str: ...
    async def create_branch(self, name: str) -> None: ...
    async def checkout(self, name: str) -> None: ...
    async def branches(self) -> list[dict[str, Any]]: ...
    async def current_branch(self) -> Optional[str]: ...

    # --- disaster recovery (rebuild metadata from the content store) ---
    async def rebuild(self) -> dict[str, Any]: ...
    async def scan(self) -> dict[str, Any]: ...

    # --- schema / migrations ---
    # origofs migrates its own metadata schema forward automatically on open; these
    # expose that for introspection/operator control. Forward-only, idempotent.
    async def schema_version(self) -> dict[str, Any]: ...  # {current, latest, up_to_date}
    async def migrate(self) -> dict[str, Any]: ...  # {from, to, migrated}

    # --- attribution ---
    async def create_human(self, name: str, auth_subject: Optional[str] = None) -> int: ...
    async def create_agent(self, name: str, model: str, controller: Optional[int] = None) -> int: ...
    async def actor_by_subject(self, subject: str) -> Optional[dict[str, Any]]: ...
    async def actor(self, id: int) -> Optional[dict[str, Any]]: ...  # resolve an actor_id
    async def list_actors(self) -> list[dict[str, Any]]: ...  # every actor, oldest first
    async def find_or_create_human(self, auth_subject: str, display_name: str) -> int: ...
    async def find_or_create_agent(self, auth_subject: str, display_name: str, model: str, controller: Optional[int] = None) -> int: ...
    async def create_session(self, actor_id: int, client: Optional[str] = None) -> int: ...
    # Each blame span is a dict with `byte_start`/`byte_end` (the ground-truth byte
    # range), the derived `line_start`/`line_end`, `session`, and `actor`.
    async def blame(self, path: str) -> list[dict[str, Any]]: ...

    # --- live co-editing (M8) ---
    async def open_coedit(self, ctx: WriteCtx, path: str) -> CoeditDoc: ...
    async def checkpoint_coedit(self, ctx: WriteCtx, path: str, doc: CoeditDoc) -> None: ...
    # Cross-worker relay (Postgres-backed workspaces). `is_postgres` gates it.
    def is_postgres(self) -> bool: ...
    async def coedit_relay_init(self) -> None: ...
    async def coedit_publish(self, path: str, origin: str, delta: bytes) -> None: ...
    async def coedit_replay(self, path: str) -> list[CoeditRelayNote]: ...
    async def coedit_subscribe(self) -> CoeditRelaySub: ...

    # --- live collaboration ---
    async def watch(self, after_seq: int = 0) -> list[dict[str, Any]]: ...
    async def subscribe(self, after_seq: int = 0, branch: Optional[str] = None) -> Subscription: ...
    async def presence(self, window_secs: int = 60) -> list[dict[str, Any]]: ...
    async def touch(self, actor_id: int, session_id: int, path: Optional[str] = None) -> None: ...

    # --- agent-suggestion review queue ---
    async def suggest(self, ctx: WriteCtx, path: str, data: bytes, summary: Optional[str] = None) -> int: ...
    async def suggest_delete(self, ctx: WriteCtx, path: str, summary: Optional[str] = None) -> int: ...
    async def list_suggestions(self, status: Optional[str] = None, path: Optional[str] = None) -> list[dict[str, Any]]: ...
    async def get_suggestion(self, id: int) -> Optional[dict[str, Any]]: ...
    async def suggestion_diff(self, id: int) -> str: ...
    async def suggestion_content(self, id: int) -> dict[str, Any]: ...  # {base, proposed}
    async def accept_suggestion(self, id: int, approver: WriteCtx) -> None: ...
    async def reject_suggestion(self, id: int, approver: WriteCtx) -> None: ...

    # --- mounting / serving (Unix only) ---
    # FUSE/NFS are Unix-only; on Windows these raise OSError. Use the HTTP API
    # (origofs.fastapi) or embed the SDK there instead.
    def mount(self, mountpoint: str) -> Mount: ...
    async def serve_nfs(self, addr: str) -> None: ...

def fuse_mountable() -> bool:
    """Whether a FUSE mount is possible here (``/dev/fuse`` present). Always
    ``False`` off Unix (no FUSE)."""
    ...
