//! Dual-dialect schema migrations (`docs/DESIGN.md` §4b).
//!
//! One ordered list of migrations, each carrying the SQL for both dialects. Every
//! backend applies the steps it hasn't yet recorded in `schema_meta`, so SQLite
//! and Postgres stay in lockstep from a single source of truth.

/// One migration step, with the SQL for each supported engine.
pub struct Migration {
    pub version: i64,
    pub sqlite: &'static str,
    pub postgres: &'static str,
}

/// The ordered migration list. Append new steps; never edit an applied one.
pub const MIGRATIONS: &[Migration] = &[
    Migration {
        version: 1,
        sqlite: SQLITE_V1,
        postgres: POSTGRES_V1,
    },
    // V2 — versioning: refs (branches/tags/HEAD) and workspace config. The SQL is
    // identical across dialects (plain TEXT columns).
    Migration {
        version: 2,
        sqlite: V2,
        postgres: V2,
    },
    // V3 — merge: recorded conflicts and git-LFS-style exclusive file locks.
    Migration {
        version: 3,
        sqlite: V3,
        postgres: V3,
    },
    // V4 — attribution: actors, sessions, tool-call audit, the edit-op log, and
    // per-file line authorship. Dialects differ only in the identity columns.
    Migration {
        version: 4,
        sqlite: V4_SQLITE,
        postgres: V4_POSTGRES,
    },
    // V5 — live collaboration: an append-only change feed and per-session
    // presence. Dialects differ only in the identity columns.
    Migration {
        version: 5,
        sqlite: V5_SQLITE,
        postgres: V5_POSTGRES,
    },
    // V6 — branch-scoped change feed: tag each event with the branch it happened
    // on so a UI showing `main` can attribute/filter edits per branch. Plain
    // `ADD COLUMN` in both dialects.
    Migration {
        version: 6,
        sqlite: V6_SQLITE,
        postgres: V6_POSTGRES,
    },
    // V7 — agent-suggestion review queue: proposed edits held for human review.
    // Content lives in the CAS (base/proposed are content hashes); this table is
    // just the review record. Dialects differ only in the identity/int columns.
    Migration {
        version: 7,
        sqlite: V7_SQLITE,
        postgres: V7_POSTGRES,
    },
    // V8 — blame keyed by content hash (blob version) rather than by inode, so
    // per-line authorship survives checkout/merge (the inode is rebuilt, but the
    // content hash it points at carries the blame) and can never desync from the
    // content it describes. Identical SQL in both dialects (a plain TEXT key).
    Migration {
        version: 8,
        sqlite: V8,
        postgres: V8,
    },
    // V9 — one actor per external identity: a partial UNIQUE index on
    // `auth_subject` (ignoring NULLs), so an app can map its own user id to an
    // actor idempotently and `find_or_create_actor` is race-safe. Identical SQL in
    // both dialects (both support partial unique indexes).
    Migration {
        version: 9,
        sqlite: V9,
        postgres: V9,
    },
];

/// The highest migration version this build knows about — the schema version a
/// freshly-opened (or migrated) workspace is brought up to. Compare against a
/// store's [`MetadataStore::schema_version`](crate::MetadataStore::schema_version)
/// to tell whether it needs migrating.
pub fn latest_schema_version() -> i64 {
    match MIGRATIONS.last() {
        Some(m) => m.version,
        None => 0,
    }
}

// V8 — per-blob-version blame (see the migration entry above).
const V8: &str = "
CREATE TABLE IF NOT EXISTS blob_blame(
    content_hash TEXT PRIMARY KEY,
    runs         TEXT NOT NULL
);
";

// V9 — at most one actor per external identity (see the migration entry above).
const V9: &str = "
CREATE UNIQUE INDEX IF NOT EXISTS idx_actor_auth_subject
    ON actor(auth_subject) WHERE auth_subject IS NOT NULL;
";

// SQLite has no `ADD COLUMN IF NOT EXISTS`; the migration runner tolerates a
// re-applied ADD COLUMN (duplicate-column) so a re-run is idempotent. Postgres
// expresses idempotency directly.
const V6_SQLITE: &str = "ALTER TABLE fs_event ADD COLUMN branch TEXT;";
const V6_POSTGRES: &str = "ALTER TABLE fs_event ADD COLUMN IF NOT EXISTS branch TEXT;";

const V7_SQLITE: &str = "
CREATE TABLE IF NOT EXISTS suggestion(
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_id      INTEGER NOT NULL,
    session_id    INTEGER,
    branch        TEXT,
    path          TEXT NOT NULL,
    base_hash     TEXT,
    proposed_hash TEXT,
    summary       TEXT,
    status        TEXT NOT NULL,
    created_ts    INTEGER NOT NULL,
    resolved_ts   INTEGER,
    resolved_by   INTEGER
);
CREATE INDEX IF NOT EXISTS idx_suggestion_status ON suggestion(status);
CREATE INDEX IF NOT EXISTS idx_suggestion_path ON suggestion(path);
";

const V7_POSTGRES: &str = "
CREATE TABLE IF NOT EXISTS suggestion(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id      BIGINT NOT NULL,
    session_id    BIGINT,
    branch        TEXT,
    path          TEXT NOT NULL,
    base_hash     TEXT,
    proposed_hash TEXT,
    summary       TEXT,
    status        TEXT NOT NULL,
    created_ts    BIGINT NOT NULL,
    resolved_ts   BIGINT,
    resolved_by   BIGINT
);
CREATE INDEX IF NOT EXISTS idx_suggestion_status ON suggestion(status);
CREATE INDEX IF NOT EXISTS idx_suggestion_path ON suggestion(path);
";

const V5_SQLITE: &str = "
CREATE TABLE IF NOT EXISTS fs_event(
    seq        INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_id   INTEGER,
    session_id INTEGER,
    kind       TEXT NOT NULL,
    path       TEXT NOT NULL,
    detail     TEXT,
    ts         INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fs_event_seq ON fs_event(seq);
CREATE TABLE IF NOT EXISTS presence(
    session_id INTEGER PRIMARY KEY,
    actor_id   INTEGER NOT NULL,
    path       TEXT,
    last_seen  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_presence_last_seen ON presence(last_seen);
";

const V5_POSTGRES: &str = "
CREATE TABLE IF NOT EXISTS fs_event(
    seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id   BIGINT,
    session_id BIGINT,
    kind       TEXT NOT NULL,
    path       TEXT NOT NULL,
    detail     TEXT,
    ts         BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_fs_event_seq ON fs_event(seq);
CREATE TABLE IF NOT EXISTS presence(
    session_id BIGINT PRIMARY KEY,
    actor_id   BIGINT NOT NULL,
    path       TEXT,
    last_seen  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_presence_last_seen ON presence(last_seen);
";

const V2: &str = "
CREATE TABLE IF NOT EXISTS ref(
    name  TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS config(
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
";

const V3: &str = "
CREATE TABLE IF NOT EXISTS conflict(
    path TEXT PRIMARY KEY,
    kind TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS file_lock(
    path        TEXT PRIMARY KEY,
    owner       TEXT NOT NULL,
    acquired_at BIGINT NOT NULL
);
";

const V4_SQLITE: &str = "
CREATE TABLE IF NOT EXISTS actor(
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    kind                TEXT NOT NULL,
    display_name        TEXT NOT NULL,
    auth_subject        TEXT,
    agent_model         TEXT,
    agent_vendor        TEXT,
    controller_actor_id INTEGER,
    created_at          INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS session(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_id   INTEGER NOT NULL,
    client     TEXT,
    started_at INTEGER NOT NULL,
    ended_at   INTEGER
);
CREATE TABLE IF NOT EXISTS tool_calls(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id   INTEGER,
    actor_id     INTEGER,
    name         TEXT NOT NULL,
    parameters   TEXT,
    result       TEXT,
    error        TEXT,
    started_at   INTEGER NOT NULL,
    completed_at INTEGER NOT NULL,
    duration_ms  INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS edit_op(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id   INTEGER,
    actor_id     INTEGER NOT NULL,
    tool_call_id INTEGER,
    ino          INTEGER NOT NULL,
    path         TEXT NOT NULL,
    op           TEXT NOT NULL,
    byte_start   INTEGER NOT NULL,
    byte_len     INTEGER NOT NULL,
    pre_hash     TEXT,
    post_hash    TEXT,
    ts           INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_edit_op_actor ON edit_op(actor_id);
CREATE INDEX IF NOT EXISTS idx_edit_op_session ON edit_op(session_id);
CREATE TABLE IF NOT EXISTS line_blame(
    ino  INTEGER PRIMARY KEY,
    runs TEXT NOT NULL
);
";

const V4_POSTGRES: &str = "
CREATE TABLE IF NOT EXISTS actor(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                TEXT NOT NULL,
    display_name        TEXT NOT NULL,
    auth_subject        TEXT,
    agent_model         TEXT,
    agent_vendor        TEXT,
    controller_actor_id BIGINT,
    created_at          BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS session(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id   BIGINT NOT NULL,
    client     TEXT,
    started_at BIGINT NOT NULL,
    ended_at   BIGINT
);
CREATE TABLE IF NOT EXISTS tool_calls(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT,
    actor_id     BIGINT,
    name         TEXT NOT NULL,
    parameters   TEXT,
    result       TEXT,
    error        TEXT,
    started_at   BIGINT NOT NULL,
    completed_at BIGINT NOT NULL,
    duration_ms  BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS edit_op(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT,
    actor_id     BIGINT NOT NULL,
    tool_call_id BIGINT,
    ino          BIGINT NOT NULL,
    path         TEXT NOT NULL,
    op           TEXT NOT NULL,
    byte_start   BIGINT NOT NULL,
    byte_len     BIGINT NOT NULL,
    pre_hash     TEXT,
    post_hash    TEXT,
    ts           BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_edit_op_actor ON edit_op(actor_id);
CREATE INDEX IF NOT EXISTS idx_edit_op_session ON edit_op(session_id);
CREATE TABLE IF NOT EXISTS line_blame(
    ino  BIGINT PRIMARY KEY,
    runs TEXT NOT NULL
);
";

const SQLITE_V1: &str = "
CREATE TABLE IF NOT EXISTS inode(
    ino          INTEGER PRIMARY KEY AUTOINCREMENT,
    kind         TEXT    NOT NULL,
    mode         INTEGER NOT NULL,
    nlink        INTEGER NOT NULL DEFAULT 1,
    size         INTEGER NOT NULL DEFAULT 0,
    content_hash TEXT,
    mtime        INTEGER NOT NULL,
    ctime        INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS dentry(
    parent_ino INTEGER NOT NULL,
    name       TEXT    NOT NULL,
    ino        INTEGER NOT NULL,
    PRIMARY KEY(parent_ino, name)
);
CREATE INDEX IF NOT EXISTS idx_dentry_ino ON dentry(ino);
CREATE TABLE IF NOT EXISTS symlink(
    ino    INTEGER PRIMARY KEY,
    target TEXT NOT NULL
);
";

const POSTGRES_V1: &str = "
CREATE TABLE IF NOT EXISTS inode(
    ino          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         TEXT   NOT NULL,
    mode         BIGINT NOT NULL,
    nlink        BIGINT NOT NULL DEFAULT 1,
    size         BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT,
    mtime        BIGINT NOT NULL,
    ctime        BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS dentry(
    parent_ino BIGINT NOT NULL,
    name       TEXT   NOT NULL,
    ino        BIGINT NOT NULL,
    PRIMARY KEY(parent_ino, name)
);
CREATE INDEX IF NOT EXISTS idx_dentry_ino ON dentry(ino);
CREATE TABLE IF NOT EXISTS symlink(
    ino    BIGINT PRIMARY KEY,
    target TEXT NOT NULL
);
";
