"""Type stubs for the origo package (re-exported from the ``origo._origo`` extension).

Every I/O method is async (returns an awaitable) so it composes with FastAPI's
`async def` handlers. Structured results are plain ``dict``/``list`` objects,
directly JSON-serializable.
"""
from __future__ import annotations
from typing import Any, Optional

__version__: str

class OrigoError(Exception):
    """Base origo error (raised for errors without a more specific mapping)."""

class ConflictError(OrigoError):
    """A suggestion's base changed since it was proposed (stale base)."""

class WriteCtx:
    """The actor context to attribute a write to."""
    @staticmethod
    def actor(actor: int) -> "WriteCtx": ...
    @staticmethod
    def session(actor: int, session: int) -> "WriteCtx": ...
    @property
    def actor_id(self) -> int: ...
    @property
    def session_id(self) -> Optional[int]: ...

class S3Config:
    """Connection settings for an S3-compatible object store (S3/R2/MinIO, or GCS
    via its S3-interop XML API). For GCS, set ``endpoint`` to
    ``https://storage.googleapis.com`` and pass GCS HMAC interop keys; for native
    GCS auth use :class:`GcsConfig` instead."""
    def __init__(
        self,
        bucket: str,
        region: str,
        endpoint: Optional[str] = None,
        allow_http: bool = False,
        access_key_id: Optional[str] = None,
        secret_access_key: Optional[str] = None,
        prefix: Optional[str] = None,
    ) -> None: ...

class GcsConfig:
    """Connection settings for a native Google Cloud Storage object store (GCS JSON
    API + OAuth2). Credentials resolve as: explicit ``service_account_key`` (inline
    JSON) or ``service_account_path`` (file); then Application Default Credentials
    (``application_credentials``, else ``GOOGLE_APPLICATION_CREDENTIALS`` /
    ``gcloud``); then the GCE/GKE metadata server (workload identity)."""
    def __init__(
        self,
        bucket: str,
        service_account_path: Optional[str] = None,
        service_account_key: Optional[str] = None,
        application_credentials: Optional[str] = None,
        prefix: Optional[str] = None,
    ) -> None: ...

class Mount:
    """A live FUSE mount; unmounts on ``unmount()``, ``with``-exit, or drop."""
    def unmount(self) -> None: ...
    def __enter__(self) -> "Mount": ...
    def __exit__(self, *args: Any) -> None: ...

class Subscription:
    """A push subscription to the change feed (Postgres LISTEN/NOTIFY)."""
    async def recv(self) -> list[dict[str, Any]]: ...

class Workspace:
    # --- constructors (async) ---
    @staticmethod
    async def open_local(db_path: str, cas_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_local_packed(db_path: str, data_dir: str, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg(dsn: str, cas_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_s3(db_path: str, cfg: S3Config) -> "Workspace": ...
    @staticmethod
    async def open_s3_packed(db_path: str, cfg: S3Config, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg_s3(dsn: str, cfg: S3Config) -> "Workspace": ...
    @staticmethod
    async def open_pg_s3_packed(dsn: str, cfg: S3Config, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_gcs(db_path: str, cfg: GcsConfig) -> "Workspace": ...
    @staticmethod
    async def open_gcs_packed(db_path: str, cfg: GcsConfig, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg_gcs(dsn: str, cfg: GcsConfig) -> "Workspace": ...
    @staticmethod
    async def open_pg_gcs_packed(dsn: str, cfg: GcsConfig, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_object_memory(db_path: str) -> "Workspace": ...

    # --- files ---
    async def read(self, path: str) -> bytes: ...
    async def write(self, path: str, data: bytes) -> None: ...
    async def write_as(self, ctx: WriteCtx, path: str, data: bytes) -> None: ...
    async def mkdir_p(self, path: str) -> None: ...
    async def ls(self, path: str) -> list[dict[str, Any]]: ...
    async def stat(self, path: str) -> dict[str, Any]: ...
    async def remove(self, path: str) -> None: ...
    async def rename(self, from_: str, to: str) -> None: ...

    # --- versioning ---
    async def commit(self, author: str, message: str) -> str: ...
    async def log(self) -> list[dict[str, Any]]: ...
    async def status(self) -> list[dict[str, Any]]: ...
    async def diff(self, from_: str, to: str) -> list[dict[str, Any]]: ...
    async def diff_file(self, from_: str, to: str, path: str) -> str: ...
    async def create_branch(self, name: str) -> None: ...
    async def checkout(self, name: str) -> None: ...
    async def branches(self) -> list[dict[str, Any]]: ...
    async def current_branch(self) -> Optional[str]: ...

    # --- disaster recovery (rebuild metadata from the content store) ---
    async def rebuild(self) -> dict[str, Any]: ...
    async def scan(self) -> dict[str, Any]: ...

    # --- schema / migrations ---
    # origo migrates its own metadata schema forward automatically on open; these
    # expose that for introspection/operator control. Forward-only, idempotent.
    async def schema_version(self) -> dict[str, Any]: ...  # {current, latest, up_to_date}
    async def migrate(self) -> dict[str, Any]: ...  # {from, to, migrated}

    # --- attribution ---
    async def create_human(self, name: str, auth_subject: Optional[str] = None) -> int: ...
    async def create_agent(self, name: str, model: str, controller: Optional[int] = None) -> int: ...
    async def actor_by_subject(self, subject: str) -> Optional[dict[str, Any]]: ...
    async def actor(self, id: int) -> Optional[dict[str, Any]]: ...  # resolve an actor_id
    async def list_actors(self) -> list[dict[str, Any]]: ...  # every actor, oldest first
    async def find_or_create_human(self, auth_subject: str, display_name: str) -> int: ...
    async def find_or_create_agent(self, auth_subject: str, display_name: str, model: str, controller: Optional[int] = None) -> int: ...
    async def create_session(self, actor_id: int, client: Optional[str] = None) -> int: ...
    async def blame(self, path: str) -> list[dict[str, Any]]: ...

    # --- live collaboration ---
    async def watch(self, after_seq: int = 0) -> list[dict[str, Any]]: ...
    async def subscribe(self, after_seq: int = 0, branch: Optional[str] = None) -> Subscription: ...
    async def presence(self, window_secs: int = 60) -> list[dict[str, Any]]: ...
    async def touch(self, actor_id: int, session_id: int, path: Optional[str] = None) -> None: ...

    # --- agent-suggestion review queue ---
    async def suggest(self, ctx: WriteCtx, path: str, data: bytes, summary: Optional[str] = None) -> int: ...
    async def suggest_delete(self, ctx: WriteCtx, path: str, summary: Optional[str] = None) -> int: ...
    async def list_suggestions(self, status: Optional[str] = None, path: Optional[str] = None) -> list[dict[str, Any]]: ...
    async def get_suggestion(self, id: int) -> Optional[dict[str, Any]]: ...
    async def suggestion_diff(self, id: int) -> str: ...
    async def suggestion_content(self, id: int) -> dict[str, Any]: ...  # {base, proposed}
    async def accept_suggestion(self, id: int, approver: WriteCtx) -> None: ...
    async def reject_suggestion(self, id: int, approver: WriteCtx) -> None: ...

    # --- mounting / serving (Unix only) ---
    # FUSE/NFS are Unix-only; on Windows these raise OSError. Use the HTTP API
    # (origo.fastapi) or embed the SDK there instead.
    def mount(self, mountpoint: str) -> Mount: ...
    async def serve_nfs(self, addr: str) -> None: ...

def fuse_mountable() -> bool:
    """Whether a FUSE mount is possible here (``/dev/fuse`` present). Always
    ``False`` off Unix (no FUSE)."""
    ...
